<div class="projectsList">
    <div>
        <div class="clearfix">
            <div class="fleft">
                <ul class="projectsListNav">
                    <li><a href="#">Active</a></li>
                    <li><a href="#">Closed</a></li>
                    <li class="activeMenu"><a href="#">All</a></li>
                </ul>
            </div>

            <div class="fright">
                <div class="search" id="search">
                    <input type="text" name="search" placeholder="Search" ng-model="search._title">
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        tmApp.controller('ProjectsListCtrl', function($scope) {
            $scope.projects = <?php echo $this->projects; ?>;
        });
    </script>

    <div class="clearfix projectsListContent" ng-controller="ProjectsListCtrl">
        <div class="projectContent" ng-repeat="project in projects | filter:search">
            <div class="clearfix projectHeader">
                <div class="fleft" style="width: 95%">
                    <span id="{{project._id}}" class="projectTitle"> {{project._title}} </span>
                </div>
                <div class="fright">
                    <a class="primary mediumButton" href="/project/edit/id/{{project._id}}">Edit</a>
                </div>
            </div>

            <div class="projectDetails clearfix">
                <div class="projectSummary"><span class="colTitle">Summary: </span> {{project._summary}} </div>

                <div class="projectData">
                    <div class="projectDataCol fleft">
                        <div class="projectTag">
                            <span class="colTitle">Tag: </span> {{project._hashTag}}
                        </div>
                        <div class="projectLastUpdate">
                            <span class="colTitle">Last Updated On: </span> {{project._lastUpdatedOn}}
                        </div>
                    </div>

                    <div class="projectDataCol fleft">
                        <div class="projectTweets">
                            <span class="colTitle">No: of Tweets: </span> {{project._numOfTweets}}
                        </div>
                        <div class="projectInstagramPosts">
                            <span class="colTitle">No: of Instagram Posts: </span> {{project._numOfPosts}}
                        </div>
                    </div>

                    <div class="projectDataCol fleft">
                        <div class="projectTweets">
                            <span class="colTitle">Status: </span> <span class="{{project._status|lowercase}}"> {{project._status}} </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.projectHeader div:nth-child(1)').click(function(event) {
            var url = $(location).attr('protocol') + '//' + $(location).attr('hostname') + '/project/view/id/' + $(this).children('span')[0].id;
            $(location).attr('href', url);
        });

        // Add active class for projects navigation menu
        $('nav li a#projectNav').addClass('active');
    });
</script>