<div class="clearfix home-page">
    <p>The TweetMap system is designed to allow for the rapid creation of citizen science environments.
        The system allows you to define custom Twitter and Instagram tags that users can tweet.
        The custom tags will be aggregated and displayed to a Google Map, displaying the user tweeted data from any variety of user locations.
    </p>

    <ul class="bulletList">
        <li class="bulletPoint">Use TweetMap as part of your science class to show students how they can engage with science via Twitter and Instagram!</li>
        <li class="bulletPoint">Use TweetMap to set up a custom citizen science project for your own research projects!</li>
        <li class="bulletPoint">Download the TweetMap source code and install it on your own system!</li>
        <li class="bulletPoint">Contribute to TweetMap as an open source project in the advancement of citizen science!</li>
    </ul>
    <br />
    <p>If you have questions, please feel free to contact us (<a href="mailto:mgermonprez@unomaha.edu">mgermonprez@unomaha.edu</a>). We are happy to help.</p>

    <div id="newProjectButton" class="navButton">
        <a href="/project/create" class="primary mediumButton">Create New Project</a>
    </div>

    <br /><br />
    <p class="copyrightHomePage">Team | Contact Us | College of IS&T | Source Code | Copyright and Licensing</p>

    <script type="text/javascript">
        $(document).ready(function () {
            $('nav li a#homeNav').addClass('active');
            $('#newProjectNavButton').hide();
        });
    </script>
</div>