<?php echo $this->doctype(); ?>
<html lang="en" ng-app="tmApp">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Set Title-->
    <?php echo $this->headTitle(); ?>

    <!-- Load Stylesheets -->
    <?php echo $this->headLink(); ?>

    <!-- Load Javascript Libs -->
    <?php echo $this->headScript(); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!----------- Header Start ----------->
    <div id="header">
        <!-- Header Left -->
        <div class="headerleft">
            <div class="logo">
                <a href="/"><h1>TweetMap</h1></a>
            </div>

            <nav class="menu">
                <ul>
                    <li><a href="/" id="homeNav">Home</a></li>
                    <li><a href="/projects" id="projectNav">Projects</a></li>
                </ul>
            </nav>
        </div>

        <!-- Header Right -->
        <div class="headerright fright" id="newProjectNavButton">
            <div class="navButton">
                <a href="/project/create" class="primary mediumButton">Create New Project</a>
            </div>
        </div>
    </div>
    <!----------- Header End ----------->

    <!----------- Body Start ----------->
    <div class="mainContainer">
        <div class="loading" id="loading"> </div>
        <div id="notification">
            <div class="" style="display: none;"></div>
        </div>
        <?php echo $this->layout()->content; ?>
    </div>
    <!----------- Body End ----------->

    <!----------- Footer Start ----------->
    <div id="footer">
        <p>&copy; 2014, University of Nebraska Omaha.</p>
    </div>
    <!----------- Footer End ----------->
</body>
</html>