<div class="createEditProject">
    <h2 class="newProject"><?php echo (empty($this->id)) ? 'New Project' : 'Edit Project'; ?></h2>
    <?php echo $this->message; ?>
    <form action="<?php echo (empty($this->id)) ? '/project/create' : '/project/edit/id/'.$this->id; ?>" method="POST" autocomplete="off">

        <?php if($this->hasError) { ?>
            <div class="errorMsg">Please input all the required fields.</div>
        <?php } ?>

        <div class="userForm">
            <div class="clearfix formGrp">
                <label class="inputLabel">Title <span class="required">*</span></label>
                <div class="inputEle">
                    <input id="title" type="text" name="title" size="50" placeholder="Enter your project title" value="<?php echo ($this->title) ? $this->title : '';?>" />
                </div>
            </div>

            <div class="clearfix formGrp">
                <label class="inputLabel">Hash tag <span class="required">*</span></label>
                <div class="inputEle">
                    # <input type="text" name="hashTag" size="48" placeholder="Enter your project HashTag" id="hashTag" value="<?php echo ($this->hashTag) ? ltrim($this->hashTag, '#') : '';?>" />
                </div>
            </div>

            <div class="clearfix formGrp">
                <label class="inputLabel">Summary <span class="required">*</span></label>
                <div class="inputEle">
                    <input type="text" name="summary" id="summary" size="50" placeholder="Brief description of your project" value="<?php echo ($this->summary) ? $this->summary : '';?>" />
                </div>
            </div>

            <div class="clearfix formGrp">
                <label class="inputLabel">Description <span class="required">*</span></label>
                <div class="inputEle">
                    <textarea name="description" id="description" cols="75" rows="10" placeholder="Detailed description of your project"><?php echo ($this->description) ? $this->description : '';?></textarea>
                </div>
            </div>

            <div class="clearfix formGrp">
                <label class="inputLabel">Project Date Range <span class="required">*</span></label>
                <div class="inputEle">
                    <input type="text" value="<?php echo ($this->startDateTime) ? $this->startDateTime : '';?>" placeholder="Start Date & Time" size="30" name="startDateTime" id="startDateTime" readonly /> -
                    <input type="text" value="<?php echo ($this->endDateTime) ? $this->endDateTime : '';?>" placeholder="End Date & Time" size="30" name="endDateTime" id="endDateTime" readonly />
                </div>
            </div>

            <div class="sectionGrp">
                <div class="sectionTitle">Which of the following services you wish to use? <span class="required">*</span></div>
                <div class="clearfix formGrp">
                    <div class="inputLabel">
                        <input type="checkbox" name="useTwitter" size="50" <?php echo ($this->useTwitter) ? 'checked' : '';?> />
                    </div>
                    <label class="inputEle">Twitter</label>
                </div>

                <div class="clearfix formGrp">
                    <div class="inputLabel">
                        <input type="checkbox" name="useInstagram" size="50" <?php echo ($this->useInstagram) ? 'checked' : '';?> />
                    </div>
                    <label class="inputEle">Instagram</label>
                </div>
            </div>

            <div class="sectionGrp trackInfo">
                <div class="sectionTitle">What do you want to track? <span class="required">*</span></div>
                <div id="trackDiv">
                    <?php
                    if(!empty($this->trackData)) {
                        foreach($this->trackData as $trackName => $trackValue) {
                    ?>
                            <div class="clearfix formGrp trackGrp">
                                <div class="inputLabel">
                                    <input type="text" name="trackName[]" id="" placeholder="Name" class="trackName" value="<?php echo $trackName ?>" />
                                </div>
                                <div class="inputEle">
                                    <input type="text" name="trackValue[]" size="50" id="" placeholder="Example Value" class="trackvalue" value="<?php echo $trackValue ?>" />
                                </div>
                            </div>
                        <?php }
                    } else { ?>
                        <div class="clearfix formGrp trackGrp">
                            <div class="inputLabel">
                                <input type="text" name="trackName[]" id="" placeholder="Name" class="trackName" value="" />
                            </div>
                            <div class="inputEle">
                                <input type="text" name="trackValue[]" size="50" id="" placeholder="Example Value" class="trackvalue" value="" />
                            </div>
                        </div>
                    <?php } ?>
                </div>

                <input type="button" class="primary mediumButton addMore" value="Add More" id="addMore" />
            </div>

            <div>
                <div class="clearfix formGrp">
                    <label class="inputLabel">Tweet Format <span class="required">*</span></label>
                    <div class="inputEle">
                        <input type="text" name="tweetFormat" size="50" id="tweetFormat" placeholder="Your tweet format" value="<?php echo ($this->tweetFormat) ? $this->tweetFormat : '';?>" />
                    </div>
                </div>
            </div>

            <div class="formSubmitButtons">
                <input type="submit" class="primary mediumButton" id="createProj" name="submit" value="<?php echo (!empty($this->id)) ? 'Update' : 'Create'; ?>" />
                <input type="button" class="primary mediumButton" id="cancelProj" value="Cancel" />
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    function generateTweetFormat() {
        var hashTag = $("input#hashTag").val();
        if(!hashTag) {
            $('#tweetFormat').val('');
            return;
        }

        hashTag = '#' + hashTag;
        var trackNameStr = '';
        $('.trackName').each(function(index, ele) {
            if(ele.value) {
                trackNameStr = trackNameStr + ' ' + ele.value.trim();
            }
        });

        $('#tweetFormat').val(hashTag + trackNameStr);
    }

    $(document).ready(function () {
        // Hide "Create New Project" Button
        $('#newProjectNavButton').hide();

        // Add functionality for cancel button
        $('#cancelProj').click(function() {
            var url = "<?php echo $this->onProjCancel; ?>";
            $(location).attr('href', url);
        });

        // Add functionality for "Add More" button
        $("#addMore").click(function() {
            var length = $(".trackGrp").length + 1;
            var html = '<div class="clearfix formGrp trackGrp">' +
                            '<div class="inputLabel">' +
                                '<input type="text" name="trackName[]" id="" placeholder="Name" class="trackName" />' +
                            '</div>' +
                            '<div class="inputEle">' +
                                '<input type="text" name="trackValue[]" size="50" id="" placeholder="Example Value" class="trackvalue" />' +
                            '</div>' +
                        '</div>';

            $('#trackDiv').append(html);
            $('#trackDiv div:nth-child('+ length +')').focusout(function(event) {
                generateTweetFormat();
            });
        });

        // Auto Suggest hashtag based on project title
        $("input#title").focusout(function(event) {
            var hashTag = this.value.replace(/\s+/g, "").toLowerCase();
            $("input#hashTag").val(hashTag);
            generateTweetFormat();
            event.preventDefault();
        });

        // Auto Suggest tweet format based on hashtag and track data.
        $("input#hashTag").focusout(function(event) {
            generateTweetFormat();
        });

        // Generate tweet format
        $(".trackName").focusout(function(event) {
            generateTweetFormat();
        });

        // Date and Time Picker
        var startDateTimeEle = $("#startDateTime");
        var endDateTimeEle = $("#endDateTime");
        var dateTimePickerOpts = {
            timeFormat: "hh:mm TT Z",
            dateFormat: "yy-mm-dd",
            minDate: new Date(),
            showTimezone: true
        };
        var startDateTimePickerOpts = {};
        var endDateTimePickerOpts = {};
        $.extend(startDateTimePickerOpts, dateTimePickerOpts, {onClose: function(dateText, inst) {
//            if (dateText) {
//                var startDateTime = startDateTimeEle.datetimepicker('getDate');
//                var endDateTime = endDateTimeEle.datetimepicker('getDate');
//                if(endDateTime) {
//                    $('#totalEstimatedTaskTime').html('Total Time - ' + endDateTime - startDateTime);
//                }
//            }
        }
        });
        $.extend(endDateTimePickerOpts, dateTimePickerOpts, {onClose: function(dateText, inst) {
//            if (dateText) {
//                var startDateTime = startDateTimeEle.datetimepicker('getDate');
//                var endDateTime = endDateTimeEle.datetimepicker('getDate');
//                if(startDateTime) {
//
//                }
//            }
        }
        });
        startDateTimeEle.datetimepicker(startDateTimePickerOpts);
        endDateTimeEle.datetimepicker(endDateTimePickerOpts);
    });
</script>