<div class="projectView">
    <?php echo $this->render('/project/projectlayout.phtml'); ?>

        <!-- Results Map -->
        <div class="" style="display: none;">
            <?php foreach($this->posts as $post) {
                $latitude = $post->getCoordinatesLatitude();
                $longitude = $post->getCoordinatesLongitude();

                if(!empty($longitude) && !empty($latitude)) {
            ?>
                    <div class="resultsDetails">
                        <input type="hidden" value="<?php echo $post->getId() ?>" id="postId" />
                        <input type="hidden" value="<?php echo $post->getImageURL() ?>" class="imageUrl" />
                        <input type="hidden" value="<?php echo $post->getCoordinatesLongitude() ?>" class="longitude" />
                        <input type="hidden" value="<?php echo $post->getCoordinatesLatitude() ?>" class="latitude" />
                        <div class="tweetMessage"><?php echo $post->getText() ?></div>
                    </div>
                <?php }
            } ?>
        </div>

        <div class="projectBodyContent projectMapContent">
            <div id="mapCanvas" class="projectMapCanvas">

            </div>
        </div>
    </div> <!-- Closing DIV for the tag opened in projectlayout.phtml -->
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script type="text/javascript">
    $(document).ready(function() {
        // Add active class for Dashboard menu
        $('.projectsListNav li:nth-child(3)').addClass('activeMenu');

        $(".resultsDetails").each(function(index, ele) {
            var latitude = $(ele).children('input.latitude').val();
            var longitude = $(ele).children('input.longitude').val();
            var messageOnMap = '<div class="onMapContent"> <div class="onMapTitle">' + $(ele).children('div.tweetMessage').html() + '</div>';
            var imageUrl = $(ele).children('input.imageUrl').val();
            if(imageUrl) {
                messageOnMap += '<img src="'+ imageUrl +'" width="400px" height="350px" />';
            }
            messageOnMap += '</div>';

            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(latitude, longitude),
                map: googleMap,
                html: messageOnMap
            });

            google.maps.event.addListener(marker, 'click', function() {
                infowindow.setContent(this.html);
                infowindow.open(googleMap, this);
            });
        });
    });

    <?php if(!empty($this->posts)) { ?>
        function initialize() {
            var mapCanvas = document.getElementById('mapCanvas');
            var myLatlng = new google.maps.LatLng(42.3493337, 13.398172299999942);
            var map_options = {
                center: myLatlng,
                zoom: 3,
                minZoom: 3
            }
            googleMap = new google.maps.Map(mapCanvas, map_options);

            infowindow = new google.maps.InfoWindow({
                content: "loading..."
            });
        }

        // Initialize google maps before we place markers.
        initialize();
    <?php } else { ?>
        $('#mapCanvas').html('Tweets/Posts are not available at this time.');
    <?php } ?>
</script>