<div class="projectView">
    <?php echo $this->render('/project/projectlayout.phtml'); ?>

        <!-- Results Map -->
        <div class="" style="display: none;">
            <?php foreach($this->posts as $post) {
                $latitude = $post->getCoordinatesLatitude();
                $longitude = $post->getCoordinatesLongitude();

                if(!empty($longitude) && !empty($latitude)) {
            ?>
                    <div class="resultsDetails">
                        <input type="hidden" value="<?php echo $post->getId() ?>" id="postId" />
                        <input type="hidden" value="<?php echo $post->getImageURL() ?>" class="imageUrl" />
                        <input type="hidden" value="<?php echo $post->getCoordinatesLongitude() ?>" class="longitude" />
                        <input type="hidden" value="<?php echo $post->getCoordinatesLatitude() ?>" class="latitude" />
                        <div class="tweetMessage"><?php echo $post->getText() ?></div>
                    </div>
                <?php }
            } ?>
        </div>

        <div class="projectBodyContent projectMapContent">
            <div id="mapCanvas" class="projectMapCanvas">

            </div>
        </div>
    </div> <!-- Closing DIV for the tag opened in projectlayout.phtml -->
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script src="/js/overlappingmarkerspiderfier.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        // Add active class for Dashboard menu
        $('.projectsListNav li:nth-child(3)').addClass('activeMenu');
    });

    <?php if(!empty($this->posts)) { ?>
        function initialize() {
            var mapCanvas = document.getElementById('mapCanvas');
            googleMap = new google.maps.Map(mapCanvas, {
                center: new google.maps.LatLng(42.3493337, 13.398172299999942),
                zoom: 3,
                minZoom: 3
            });

            infowindow = new google.maps.InfoWindow({
                content: "loading..."
            });

            var oms = new OverlappingMarkerSpiderfier(googleMap, {markersWontMove: true, markersWontHide: true});

            var iconWithColor = function(color) {
                return 'http://chart.googleapis.com/chart?chst=d_map_xpin_letter&chld=pin|+|' + color + '|000000|ffff00';
            }

            // Click event to show info window
            oms.addListener('click', function(marker) {
                infowindow.setContent(marker.html);
                infowindow.open(googleMap, marker);
            });

            // Add spiderfy listener
            oms.addListener('spiderfy', function(markers) {
                for(var i = 0; i < markers.length; i ++) {
                    markers[i].setIcon(iconWithColor('ffee22'));
                }
                infowindow.close();
            });

            // Add spiderfy listener
            oms.addListener('unspiderfy', function(markers) {
                for(var i = 0; i < markers.length; i ++) {
                    markers[i].setIcon(null);
                }
            });

            // Place markers with their content
            $(".resultsDetails").each(function(index, ele) {
                var latitude = $(ele).children('input.latitude').val();
                var longitude = $(ele).children('input.longitude').val();
                var messageOnMap = '<div class="onMapContent"> <div class="onMapTitle">' + $(ele).children('div.tweetMessage').html() + '</div>';
                var imageUrl = $(ele).children('input.imageUrl').val();
                if(imageUrl) {
                    messageOnMap += '<img src="'+ imageUrl +'" width="400px" height="350px" />';
                }
                messageOnMap += '</div>';

                var marker = new google.maps.Marker({
                    position: new google.maps.LatLng(latitude, longitude),
                    map: googleMap,
                    html: messageOnMap
                });
                oms.addMarker(marker);
            });
        }

        // Initialize google maps before we place markers.
        initialize();
    <?php } else { ?>
        $('#mapCanvas').html('Tweets/Posts are not available at this time.');
    <?php } ?>
</script>