<html>
    <head>
        <title> <?php echo $this->project->getTitle(); ?> </title>
        <link rel="stylesheet" type="text/css" href="/css/style.css" />
    </head>
    <body>
        <div class="printInstructionsContent">
            <p><?php echo $this->project->getDescription() ?></p>

            <div class="projectTweetFormat">
                <span class="colTitle">Tweet Format: </span> <?php echo $this->project->getTweetFormat(); ?>
            </div>

            <div class="specialInstructions">
                <div class="note">Note:</div>
                <ul>
                    <?php if($this->project->getUseTwitter() && $this->project->getUseInstagram()) { ?>
                        <li class="bulletPoint"> You can use both Twitter and Instagram to post your message.</li>
                    <?php } elseif($this->project->getUseTwitter()) { ?>
                        <li class="bulletPoint"> Use Twitter to post your message.</li>
                    <?php } elseif($this->project->getUseInstagram()) { ?>
                        <li class="bulletPoint"> Use Instagram to post your message.</li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </body>
</html>