<script type="text/javascript">
    $(document).ready(function() {
        // Add active class for projects navigation menu
        $('nav li a#projectNav').addClass('active');

        // Add event to refresh button
        $('#refreshButton').click(function(event) {
            var url = '<?php echo '/project/refresh/id/'.$this->id; ?>';
            $.ajax({url: url,
                    success: function(data) {
                        if(200 == data.statusCode) {
                            location.reload(true);
                        } else {
                            showNotification({
                                message: 'An error has occurred. Please try again later.',
                                type: 'danger',
                                duration: 3
                            });
                        }
                    }
            });
        });

        // Add event for download button
        $("#downloadButton").click(function() {
            var url = '<?php echo '/project/download/id/'.$this->id; ?>';
            $("body").append("<iframe src='" + url+ "' style='display: none;' ></iframe>");
        });

        // Close project
        $("#closeProjectButton").click(function() {
            var id = '<?php echo $this->id; ?>';
            var close = confirm("You are about to close this project. Are you sure?");
            if(close) {
                $.ajax({url: '/project/close/id/' + id,
                    type: "GET",
                    data: {},
                    dataType: "json",
                    success: function(response, textStatus, jqXHR ) {
                        if(200 == response.status.code) {
                            $('#projStatusValue').removeClass().addClass('closed').html('Closed');
                            $('#closeProjectButton').hide();
                            $('#refreshButton').hide();

                            showNotification({
                                message: response.status.message,
                                type: 'success'
                            });
                        } else {
                            showNotification({
                                message: response.status.message,
                                type: 'danger'
                            });
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown ) {
                        showNotification({
                            message: textStatus,
                            type: 'danger'
                        });
                    }
                });
            }
        });
    });
</script>

<div class="clearfix projectHeader">
    <div class="projectTitle fleft"> <?php echo $this->project->getTitle(); ?> </div>
    <div class="fright">
        <div class="fleft lastUpdate">
            <span class="colTitle"> Last Updated On: </span>
            <span id="localeLastUpdatedOn">
                <?php echo $this->postsMetaLastUpdatedOn; ?>
            </span>
        </div>

        <div class="fright">
            <div class="fleft status">
                <span class="colTitle">Status: </span>
                <span id="projStatusValue" class="<?php echo strtolower($this->project->getStatus()); ?>"> <?php echo $this->project->getStatus(); ?> </span>
            </div>
            <?php if(Application_Model_Projects::STATUS_ACTIVE == $this->project->getStatus()) { ?>
                <div class="fright" style="margin-left: 0;">
                    <img src="/img/close.png" height="20px" id="closeProjectButton" class="closeProjectButton" title="Close Project" />
                </div>
            <?php } ?>
        </div>
    </div>
</div>

<div class="projectBody"> <!-- This DIV tag should be closed by the view file where this layout was included -->
    <!-- Project navigation bar -->
    <div class="projectBodyNavBar">
        <div class="clearfix">
            <div class="fleft">
                <ul class="projectsListNav">
                    <li><a href="<?php echo '/project/view/id/'.$this->id; ?>">Dashboard</a></li>
                    <li><a href="<?php echo '/project/results/id/'.$this->id; ?>">Results</a></li>
                    <li><a href="<?php echo '/project/map/id/'.$this->id; ?>">Map</a></li>
                </ul>
            </div>

            <div class="fright rightIcons">
                <?php if(Application_Model_Projects::STATUS_ACTIVE == $this->project->getStatus()) { ?>
                    <img src="/img/refresh_green.png" height="20px" id="refreshButton" class="refreshButton" title="Refresh Results" />
                <?php } ?>
                <img src="/img/download.png" height="20px" id="downloadButton" class="downloadButton" title="Download Excel" />
            </div>
        </div>
    </div>